#define WINDOW_CLASS_NAME "Ninja Gaiden"		// Class Windows
#define MAIN_WINDOW_TITLE "Ninja Gaiden"		// Title
#define SCREEN_WIDTH 256						
#define SCREEN_HEIGHT 176						
#define MAX_FRAME_RATE 120						// FPS
#define BACK_COLOR D3DCOLOR_XRGB(0, 0, 0)		// background BackBuffer
#define DEFAULT_FPS 120							// Frame time (Animation)
#define GRAVITY_SPEED 0.014f					// velocity
#define KEYBOARD_BUFFER_SIZE 1024
#define NUMBER_MAP_LEVEL 3
#define TILE_SIZE 16

#define player Player::GetInstance()
#define PLAYER_RUNNING_SPEED 0.1f
#define PLAYER_INJURED_SPEED 0.065f
#define PLAYER_JUMPING_SPEED 0.28f
#define PLAYER_FALLING_SPEED 0.25f
#define PLAYER_CLIMBING_SPEED 0.1f
#define PLAYER_WIDTH 20
#define PLAYER_STANDING_HEIGHT 26
#define PLAYER_SITTING_HEIGHT 18

#define WEAPON_SWORD_WIDTH 32
#define WEAPON_SWORD_HEIGHT 18
#define WEAPON_BLUESHURIKEN_WIDTH 10
#define WEAPON_BLUESHURIKEN_HEIGHT 10
#define WEAPON_BLUESHURIKEN_SPEED 0.25f
#define WEAPON_REDSHURIKEN_WIDTH 15
#define WEAPON_REDSHURIKEN_HEIGHT 15
#define WEAPON_REDSHURIKEN_SPEED 0.25f
#define WEAPON_SWINGSWORD_WIDTH 18
#define WEAPON_SWINGSWORD_HEIGHT 18
#define WEAPON_BULLET_WIDTH 18
#define WEAPON_BULLET_HEIGHT 12
#define WEAPON_DAGGER_WIDTH 11
#define WEAPON_DAGGER_HEIGHT 23
#define WEAPON_FIREWHEEL_WIDTH 35
#define WEAPON_FIREWHEEL_HEIGHT 35
#define WEAPON_FIREWHEEL_SPEED 0.14f

#define HOLDER_WIDTH 20
#define HOLDER_HEIGHT 20
#define ITEM_EXISTS_TIME 2000
#define ITEM_WIDTH 20
#define ITEM_HEIGHT 20
#define ITEM_SPEED 0.14f

#define BULLET_BANSHEE_WIDTH 14
#define BULLET_BANSHEE_HEIGHT 14
#define BULLET_BANSHEE_JUMPING_SPEED 0.28f
#define BULLET_BANSHEE_FALLING_SPEED 0.25f
#define BULLET_BANSHEE_SPEED 0.08f
#define BULLET_BANSHEE_COUNT 1
#define BULLET_GUNMAN_WIDTH 8
#define BULLET_GUNMAN_HEIGHT 8
#define BULLET_GUNMAN_SPEED 0.15f
#define BULLET_GUNMAN_COUNT 3
#define BULLET_BAZOKAMAN_HEIGHT 8
#define BULLET_BAZOKAMAN_WIDTH 8
#define BULLET_BAZOKAMAN_SPEED 0.15f
#define BULLET_BAZOKAMAN_COUNT 1
#define BULLET_BOSS_WIDTH 12
#define BULLET_BOSS_HEIGHT 12
#define BULLET_BOSS_SPEED 0.1f

#define ENEMY_FROZEN_TIME 3000
#define ENEMY_SWORDMAN_WIDTH 25
#define ENEMY_SWORDMAN_HEIGHT 40
#define ENEMY_SWORDMAN_SPEED 0.02f
#define ENEMY_BAZOKAMAN_WIDTH 20
#define ENEMY_BAZOKAMAN_HEIGHT 25
#define ENEMY_BAZOKAMAN_DELAY_TIME 2500
#define ENEMY_GUNMAN_WIDTH 20
#define ENEMY_GUNMAN_HEIGHT 30
#define ENEMY_GUNMAN_SPEED 0.02f
#define ENEMY_GUNMAN_DELAY_TIME 1800
#define ENEMY_BANSHEE_WIDTH 20
#define ENEMY_BANSHEE_HEIGHT 35
#define ENEMY_BANSHEE_SPEED 0.012f
#define ENEMY_BANSHEE_DELAY_TIME 1200
#define ENEMY_DOG_WIDTH 35
#define ENEMY_DOG_HEIGHT 20
#define ENEMY_DOG_SPEED 0.14f
#define ENEMY_DOG_ACTIVE_DISTANCE 90
#define ENEMY_RUNMAN_WIDTH 18
#define ENEMY_RUNMAN_HEIGHT 32
#define ENEMY_RUNMAN_SPEED 0.17f
#define ENEMY_RUNMAN_ACTIVE_DISTANCE 85
#define ENEMY_BIRD_WIDTH 20
#define ENEMY_BIRD_HEIGHT 20
#define ENEMY_BIRD_MIN_SPEEDX 2.5f
#define ENEMY_BIRD_MIN_SPEEDY 1.5f
#define ENEMY_BIRD_DELAY_TIME 1400
#define ENEMY_BIRD_ACTIVE_DISTANCE 80
#define ENEMY_BOSS_WIDTH 36
#define ENEMY_BOSS_HEIGHT 50


#define camera Camera::GetInstance()
